---
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - resolvconf
      - gnupg
      - lsb-release
      - wireguard
      - tar
      - unattended-upgrades
    state: present

## Install docker

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
    state: present

- name: Install Docker and containerd
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Install hifis.toolkit collection
  ansible.builtin.command: ansible-galaxy collection install hifis.toolkit
  args:
    creates: ~/.ansible/collections/ansible_collections/hifis/toolkit

- name: Create docker directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /docker
    - /docker/homeassistant
    - /docker/homeassistant/config
    - /docker/homeassistant/config/homeassistant
    - /docker/homeassistant/config/homeassistant/homeassistant-config
    - /docker/homeassistant/config/zwave
    - /docker/homeassistant/config/zwave/zwave-config
    - /docker/homeassistant/config/mosquitto
    - /docker/homeassistant/config/mosquitto/config
    - /docker/homeassistant/config/mosquitto/data
    - /docker/homeassistant/config/mosquitto/log
    - /docker/homeassistant/config/zigbee2mqtt
    - /docker/homeassistant/config/zigbee2mqtt/data