unattended_upgrades_enable: true
unattended_remove_unused_dependencies: true
unattended_remove_new_unused_dependencies: true
unattended_remove_unused_kernel_packages: true
unattended_automatic_reboot: true
unattended_automatic_reboot_time: "03:00"