- hosts: localhost
  connection: local
  become: true
  roles:
    - ../roles/ha_zigbee_and_zwave
    - hifis.toolkit.unattended_upgrades
    - hifis.toolkit.ssh_keys
  vars_files:
    - ../roles/ha_zigbee_and_zwave/vars/ha-vars.yml
    - ../roles/unattended_upgrades/vars/unattended-upgrades.yml
    - ../roles/ssh_keys/vars/ssh-keys.yml